### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Parker8283** [melix/asm-bytecode-intellij#14]
http://pastebin.com/Rx9jEUbV

IntelliJ 13 CE: 13.1.14
Plugin Version: 0.3.4

**Comment by VladRassokhin** [comment]
@melix Original asm-all lib is java 1.3 compatible, repack `reloc-asm-all-5.0.2.jar` to class files version 1.6, please.
Also asm lib could be updated to 5.0.3.
