### ISSUE TITLE
Java version problem in Mac

### ISSUE THREAD

**Issue by izeye** [melix/asm-bytecode-intellij#15]
I got the following exception:
```
Plugin 'ASM Bytecode Outline' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: org/objectweb/asm/idea/config/ASMPluginComponent : Unsupported major.minor version 51.0 [Plugin: ASM Bytecode Outline]
```
How about compiling this plugin in Java 6?

Because in Mac the recommended Java version for IntelliJ is still 6 AFAIK.

**Comment by VladRassokhin** [comment]
Duplicates #14

**Comment by MastaP** [comment]
Facing the same problem. Is the project dead or we could expect a new release in the nearest future?

**Comment by melix** [comment]
It's not dead. I need to find time to release. Which is hard to find.

2015-02-06 13:14 GMT+01:00 Pavel Grigorenko <notifications@github.com>:

**Comment by melix** [comment]
I have pushed a new version of the plugin to the plugin repository. It should be visible within 48h. Once the update is done, could you please confirm to me that the issue can be closed?

**Comment by MastaP** [comment]
It's already available and totally works, thanks!

**Comment by melix** [comment]
Excellent, thanks!
