### ISSUE TITLE
Not correctly showing bytecode for inner-class of library file

### ISSUE THREAD

**Issue by master801** [melix/asm-bytecode-intellij#18]
Short explanation:
Does not correctly show the bytecode for an inner-class of a class in a library (jar-file).

More in-depth explanation:
When I open a class file from a external library (say for instance, a jar file) and it has an inner-class, when attempting to show the bytecode for the inner-class, it will instead show the bytecode for the actual class and not the inner-class.

This is not an issue for actual class files (that are made in the project), however it is an issue for classes in libraries.

Versions used:
ASM Bytecode Outline: 0.3.5
IntelliJ IDEA 15 EAP Community edition : IC-142.3926.4
Java JDK & JRE: 1.7-80 & 1.8-45

Note: The plugin worked perfectly fine when on older version of IntelliJ, except for this minor issue.

If you need more info about this, or I am perhaps not explaining the issue correctly or simply overcomplicating the issue, please let me know so I may fix it.

I'm not sure if this happens to anonymous classes, but I'd imagine that it's also happening for it, too.

**Comment by Clashsoft** [comment]
I am having the same problem, yet it has not been adressed for almost two years now.

**Comment by Clashsoft** [comment]
@master801 why did you close this? The issue still persists.

**Comment by Tankonyako** [comment]
yes this issue not fixed
